export const ACT_INIT_STORE = "ACT_INIT_STORE";
export const ACT_ADD_CANCION = "ACT_ADD_CANCION";
export const ACT_ELIMINAR_CANCION = "ACT_ELIMINAR_CANCION";
export const ACT_MODIFICAR_CANCION = "ACT_MODIFICAR_CANCION";